<a href="https://colab.research.google.com/github/y-hiroto2025/neural-network-from-scratch/blob/main/notebooks/06_simplenet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)

    y = exp_a / sum_exp_a
    return y

def cross_entropy_error(y, t):
  if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, t.size)

  if t.size == y.size:
    t = t.argmax(axis=1)

  batch_size = y.shape[0]
  delta = 1e-7

  return -np.sum(np.log(y[np.arange(batch_size), t] + delta)) / batch_size

def numerical_gradient(f, x):
    """
    勾配
    """
    h = 1e-5
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]

        x[idx] = tmp_val + h
        fxh1 = f(x)

        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
        it.iternext()

    return grad

In [3]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [4]:
net = simpleNet()

print(net.W)

[[-1.49117241 -0.97274107  0.48771292]
 [-0.30243094 -1.58658455  0.17656003]]


In [5]:
x = np.array([0.6, 0.9])
p = net.predict(x)
p

array([-1.16689129, -2.01157074,  0.45153178])

In [6]:
t = np.array([0, 0, 1])
net.loss(x, t)

np.float64(0.24949811896088647)

In [7]:
def f(W):
  return net.loss(x, t)

dW = numerical_gradient(f, net.W)
dW

array([[ 0.09266661,  0.03981839, -0.132485  ],
       [ 0.13899991,  0.05972758, -0.19872749]])